replicaCount: 3

image:
  repository: yash6712/success-it-academy
  tag: 97ce863166e30fb1aaa827290c4c2ac73ec90511
  pullPolicy: IfNotPresent
 

service:
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: helm-success-it.local

config:
  companyName: "Success IT Academy"
  environment: "Development"
  trainer: "Yash"
